"""Export figures, reproducible scripts, and session files.

A figure is not reproducible because it is pretty; it is reproducible because
somebody can regenerate it.  :func:`to_script` writes a standalone Python file
that reconstructs the exact :class:`~wedgelab.qq.QQSpec` behind a figure --
plotting-position formula included -- and re-renders it.  Drop that file in
the supplementary material and the figure stops being a claim and becomes a
computation.

Session files (:func:`to_json` / :func:`from_json`) carry the same state for
the GUI, minus the data when it came from a file on disk.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from matplotlib.figure import Figure

from wedgelab.formula import Formula, Parameter
from wedgelab.plot import PlotOptions
from wedgelab.qq import QQResult, QQSpec
from wedgelab.theme import get_theme

__all__ = [
    "VECTOR_FORMATS",
    "RASTER_FORMATS",
    "save_figure",
    "to_script",
    "to_json",
    "from_json",
    "write_session",
    "read_session",
]

VECTOR_FORMATS: tuple[str, ...] = ("pdf", "svg", "eps")
RASTER_FORMATS: tuple[str, ...] = ("png", "tif")


def save_figure(
    fig: Figure,
    path: str | Path,
    formats: Iterable[str] = ("pdf",),
    dpi: int | None = None,
) -> list[Path]:
    """Write *fig* once per requested format.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
        Figure to write.  Its physical size is preserved exactly; nothing is
        rescaled.
    path : str or Path
        Output path.  Any suffix is replaced by each format's own.
    formats : Iterable[str]
        Any of :data:`VECTOR_FORMATS` or :data:`RASTER_FORMATS`.
    dpi : int or None
        Raster resolution; ignored for vector formats.  ``None`` keeps the
        theme's setting.

    Returns
    -------
    list[Path]
        The files written.

    Raises
    ------
    ValueError
        If a requested format is not supported.
    """
    base = Path(path)
    known = set(VECTOR_FORMATS) | set(RASTER_FORMATS)
    written: list[Path] = []
    for fmt in formats:
        f = fmt.lower().lstrip(".")
        if f not in known:
            raise ValueError(
                f"unsupported format '{fmt}'; choose from {', '.join(sorted(known))}"
            )
        target = base.with_suffix(f".{f}")
        target.parent.mkdir(parents=True, exist_ok=True)
        kwargs: dict[str, Any] = {"format": f, "bbox_inches": "tight", "pad_inches": 0.02}
        if f in RASTER_FORMATS and dpi is not None:
            kwargs["dpi"] = dpi
        fig.savefig(target, **kwargs)
        written.append(target)
    return written


# ---------------------------------------------------------------------------
# Reproducible script
# ---------------------------------------------------------------------------

_SCRIPT_TEMPLATE = '''"""Reproduce a wedgelab Q-Q figure.

Generated by wedgelab. Every choice behind the figure is spelled out below:
the plotting-position formula, the reference distribution and its estimator,
the reference line, the confidence envelope, and the publication theme.

Requires wedgestats and wedgelab on the import path.
"""

import numpy as np

from wedgelab.export import save_figure
from wedgelab.formula import Formula, Parameter
from wedgelab.plot import PlotOptions, render
from wedgelab.qq import QQSpec, compute

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
{data_block}

# ---------------------------------------------------------------------------
# Plotting positions
#
# {position_doc}
# ---------------------------------------------------------------------------
position = Formula(
    name={position_name!r},
    expression={position_expr!r},
    lhs={position_lhs!r},
    description={position_desc!r},
    parameters=({position_params}),
    citation={position_citation!r},
)

# ---------------------------------------------------------------------------
# Specification
# ---------------------------------------------------------------------------
spec = QQSpec(
    data=data,
    dist_key={dist_key!r},
    fit_method={fit_method!r},
    manual_params={manual_params!r},
    position=position,
    position_bindings={bindings!r},
    line={line!r},
    envelope={envelope!r},
    alpha={alpha!r},
    standardize={standardize!r},
    detrend={detrend!r},
    bootstrap_reps={bootstrap_reps!r},
    random_state={random_state!r},
    label={label!r},
)

result = compute(spec)

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
options = PlotOptions(
    title={title!r},
    xlabel={xlabel!r},
    ylabel={ylabel!r},
    show_band={show_band!r},
    show_line={show_line!r},
    show_legend={show_legend!r},
    annotate={annotate!r},
    annotation_fields={annotation_fields!r},
    mark_outliers={mark_outliers!r},
    label_outliers={label_outliers!r},
    equal_aspect={equal_aspect!r},
    zero_line={zero_line!r},
)

fig = render(result, {theme_key!r}, options)
paths = save_figure(fig, {stem!r}, formats={formats!r})

print(result.caption())
for line in result.diagnostics.lines():
    print(line)
for path in paths:
    print("wrote", path)
'''


def _format_parameters(params: tuple[Parameter, ...]) -> str:
    """Render a parameter tuple as source code."""
    if not params:
        return ""
    parts = [
        "\n        Parameter(name={!r}, default={!r}, lower={!r}, upper={!r}, "
        "step={!r}, description={!r}),".format(
            p.name, p.default, p.lower, p.upper, p.step, p.description
        )
        for p in params
    ]
    return "".join(parts) + "\n    "


def _format_data(data: np.ndarray, data_path: str | Path | None, max_inline: int) -> str:
    """Render the data block: an inline literal, or a loader for a sidecar file."""
    if data_path is not None:
        return (
            f"# Loaded from the file this script was exported alongside.\n"
            f"data = np.loadtxt({str(data_path)!r})"
        )
    if data.size > max_inline:
        return (
            f"# {data.size} observations exceeded the inline limit of {max_inline}.\n"
            "# Export the data alongside the script and point this line at it.\n"
            'data = np.loadtxt("data.txt")'
        )
    values = ", ".join(repr(float(v)) for v in data)
    return f"data = np.array([{values}])"


def to_script(
    result: QQResult,
    theme_key: str = "screen",
    options: PlotOptions | None = None,
    *,
    stem: str = "qq_figure",
    formats: tuple[str, ...] = ("pdf", "png"),
    data_path: str | Path | None = None,
    max_inline: int = 5000,
) -> str:
    """Generate a standalone script that regenerates this figure.

    Parameters
    ----------
    result : QQResult
        The computed result to reproduce.
    theme_key : str
        Theme the figure was rendered with.
    options : PlotOptions or None
        Presentation options used.
    stem : str
        Output path stem the generated script will write to.
    formats : tuple[str, ...]
        Formats the generated script will write.
    data_path : str or Path or None
        When given, the script loads the data from this path instead of
        embedding it.
    max_inline : int
        Largest sample embedded as a literal.

    Returns
    -------
    str
        Python source.
    """
    spec = result.spec
    opts = options or PlotOptions()
    get_theme(theme_key)  # fail early on a bad theme key

    pos = spec.position
    doc = pos.description or "Plotting position rule."
    if pos.citation:
        doc = f"{doc}\n# Source: {pos.citation}"

    return _SCRIPT_TEMPLATE.format(
        data_block=_format_data(np.asarray(spec.data, dtype=float), data_path, max_inline),
        position_doc=doc,
        position_name=pos.name,
        position_expr=pos.expression,
        position_lhs=pos.lhs,
        position_desc=pos.description,
        position_params=_format_parameters(pos.parameters),
        position_citation=pos.citation,
        dist_key=spec.dist_key,
        fit_method=spec.fit_method,
        manual_params=spec.manual_params,
        bindings=dict(spec.position_bindings),
        line=spec.line,
        envelope=spec.envelope,
        alpha=spec.alpha,
        standardize=spec.standardize,
        detrend=spec.detrend,
        bootstrap_reps=spec.bootstrap_reps,
        random_state=spec.random_state,
        label=spec.label,
        title=opts.title,
        xlabel=opts.xlabel,
        ylabel=opts.ylabel,
        show_band=opts.show_band,
        show_line=opts.show_line,
        show_legend=opts.show_legend,
        annotate=opts.annotate,
        annotation_fields=opts.annotation_fields,
        mark_outliers=opts.mark_outliers,
        label_outliers=opts.label_outliers,
        equal_aspect=opts.equal_aspect,
        zero_line=opts.zero_line,
        theme_key=theme_key,
        stem=stem,
        formats=tuple(formats),
    )


# ---------------------------------------------------------------------------
# Sessions
# ---------------------------------------------------------------------------


def to_json(
    spec: QQSpec,
    theme_key: str = "screen",
    options: PlotOptions | None = None,
    *,
    include_data: bool = True,
) -> str:
    """Serialise a specification, theme, and presentation options to JSON."""
    opts = options or PlotOptions()
    pos = spec.position
    payload: dict[str, Any] = {
        "wedgelab_session": 1,
        "spec": {
            "data": [float(v) for v in np.asarray(spec.data).ravel()] if include_data else None,
            "dist_key": spec.dist_key,
            "fit_method": spec.fit_method,
            "manual_params": list(spec.manual_params) if spec.manual_params else None,
            "position": {
                "name": pos.name,
                "expression": pos.expression,
                "lhs": pos.lhs,
                "description": pos.description,
                "citation": pos.citation,
                "latex": pos.latex,
                "derived_from": pos.derived_from,
                "parameters": [asdict(p) for p in pos.parameters],
            },
            "position_bindings": {k: float(v) for k, v in spec.position_bindings.items()},
            "line": spec.line,
            "envelope": spec.envelope,
            "alpha": spec.alpha,
            "standardize": spec.standardize,
            "detrend": spec.detrend,
            "bootstrap_reps": spec.bootstrap_reps,
            "random_state": spec.random_state,
            "label": spec.label,
        },
        "theme": theme_key,
        "options": asdict(opts),
    }
    return json.dumps(payload, indent=2)


def from_json(text: str, data: np.ndarray | None = None) -> tuple[QQSpec, str, PlotOptions]:
    """Restore a session written by :func:`to_json`.

    Parameters
    ----------
    text : str
        JSON produced by :func:`to_json`.
    data : np.ndarray or None
        Sample to use when the session was saved without its data.

    Returns
    -------
    tuple[QQSpec, str, PlotOptions]
        The specification, theme key, and presentation options.

    Raises
    ------
    ValueError
        If the payload is not a wedgelab session, or carries no data and none
        was supplied.
    """
    payload = json.loads(text)
    if payload.get("wedgelab_session") != 1:
        raise ValueError("not a wedgelab session file (version 1)")

    raw = payload["spec"]
    values = raw.get("data")
    if values is None:
        if data is None:
            raise ValueError("session carries no data; supply it explicitly")
        sample = np.asarray(data, dtype=float)
    else:
        sample = np.asarray(values, dtype=float)

    pos_raw = raw["position"]
    position = Formula(
        name=pos_raw["name"],
        expression=pos_raw["expression"],
        lhs=pos_raw.get("lhs", "p_i"),
        description=pos_raw.get("description", ""),
        parameters=tuple(Parameter(**p) for p in pos_raw.get("parameters", [])),
        citation=pos_raw.get("citation", ""),
        latex=pos_raw.get("latex", ""),
        derived_from=pos_raw.get("derived_from", ""),
    )

    manual = raw.get("manual_params")
    spec = QQSpec(
        data=sample,
        dist_key=raw["dist_key"],
        fit_method=raw["fit_method"],
        manual_params=tuple(manual) if manual else None,
        position=position,
        position_bindings=dict(raw.get("position_bindings", {})),
        line=raw["line"],
        envelope=raw["envelope"],
        alpha=raw["alpha"],
        standardize=raw["standardize"],
        detrend=raw["detrend"],
        bootstrap_reps=raw["bootstrap_reps"],
        random_state=raw["random_state"],
        label=raw["label"],
    )
    return spec, payload.get("theme", "screen"), PlotOptions(**payload.get("options", {}))


def write_session(
    path: str | Path,
    spec: QQSpec,
    theme_key: str = "screen",
    options: PlotOptions | None = None,
    *,
    include_data: bool = True,
) -> Path:
    """Write a session file and return its path."""
    target = Path(path).with_suffix(".wedgelab.json")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(to_json(spec, theme_key, options, include_data=include_data), encoding="utf-8")
    return target


def read_session(
    path: str | Path, data: np.ndarray | None = None
) -> tuple[QQSpec, str, PlotOptions]:
    """Read a session file written by :func:`write_session`."""
    return from_json(Path(path).read_text(encoding="utf-8"), data)
